<?php
require_once 'includes/db.php';
require_once 'includes/user-auth.php';

// Fetch all categories
$stmt = $pdo->query("SELECT * FROM categories ORDER BY id");
$categories = $stmt->fetchAll();

// Fetch all parts
$stmt = $pdo->query("SELECT * FROM parts ORDER BY price ASC");
$all_parts = $stmt->fetchAll();

// Group parts by category slug
$parts_by_category = [];
foreach ($categories as $cat) {
    $parts_by_category[$cat['slug']] = [];
}

foreach ($all_parts as $part) {
    // Find category slug for this part
    foreach ($categories as $cat) {
        if ($cat['id'] == $part['category_id']) {
            $parts_by_category[$cat['slug']][] = $part;
            break;
        }
    }
}

// Handle Save Build
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['save_build'])) {
    requireLogin();
    
    $budget = !empty($_POST['budget']) ? $_POST['budget'] : null;
    $total_price = $_POST['total_price'];
    $cpu_id = $_POST['cpu_id'] ?: null;
    $mobo_id = $_POST['motherboard_id'] ?: null;
    $ram_id = $_POST['ram_id'] ?: null;
    $storage_id = $_POST['storage_id'] ?: null;
    $gpu_id = $_POST['gpu_id'] ?: null;
    $psu_id = $_POST['psu_id'] ?: null;

    $stmt = $pdo->prepare("INSERT INTO builds (user_id, budget, total_price, cpu_id, motherboard_id, ram_id, storage_id, gpu_id, psu_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)");
    if ($stmt->execute([$_SESSION['user_id'], $budget, $total_price, $cpu_id, $mobo_id, $ram_id, $storage_id, $gpu_id, $psu_id])) {
        header("Location: my-builds.php");
        exit();
    } else {
        $error = "Failed to save build.";
    }
}

include 'includes/header.php';
?>

<script>
    // Pass PHP data to JS
    const categories = <?php echo json_encode($categories); ?>;
    const partsData = <?php echo json_encode($parts_by_category); ?>;
</script>

<div class="d-flex gap-2" style="align-items: flex-start;">
    <!-- Main Builder Area -->
    <div style="flex: 3;">
        <div class="card">
            <div class="card-header d-flex justify-between align-center">
                <span>PC Builder</span>
                <div class="d-flex align-center gap-1">
                    <label for="budget-input">Budget: ₹</label>
                    <input type="number" id="budget-input" class="form-control" style="width: 120px;" placeholder="Optional">
                </div>
            </div>

            <!-- Progress Bar -->
            <div style="display: flex; margin-bottom: 1.5rem; background: #21262d; border-radius: 4px; overflow: hidden;">
                <?php foreach ($categories as $index => $cat): ?>
                    <div id="step-indicator-<?php echo $cat['slug']; ?>" class="step-indicator">
                        <?php echo $cat['name']; ?>
                    </div>
                <?php endforeach; ?>
            </div>

            <!-- Steps -->
            <div id="builder-steps">
                <!-- Steps will be generated by JS or we can hardcode containers -->
                <?php foreach ($categories as $cat): ?>
                    <div id="step-<?php echo $cat['slug']; ?>" class="builder-step">
                        <h3 class="mb-2">Select <?php echo $cat['name']; ?></h3>
                        <div id="list-<?php echo $cat['slug']; ?>">
                            <!-- Parts list will be injected here -->
                        </div>
                    </div>
                <?php endforeach; ?>
                
                <!-- Summary Step -->
                <div id="step-summary" class="builder-step">
                    <h3 class="mb-2">Build Summary</h3>
                    <div id="summary-content"></div>
                    
                    <?php if (isLoggedIn()): ?>
                        <form method="POST" id="save-form" class="mt-3">
                            <input type="hidden" name="save_build" value="1">
                            <input type="hidden" name="budget" id="input-budget">
                            <input type="hidden" name="total_price" id="input-total">
                            <input type="hidden" name="cpu_id" id="input-cpu">
                            <input type="hidden" name="motherboard_id" id="input-motherboard">
                            <input type="hidden" name="ram_id" id="input-ram">
                            <input type="hidden" name="storage_id" id="input-storage">
                            <input type="hidden" name="gpu_id" id="input-gpu">
                            <input type="hidden" name="psu_id" id="input-psu">
                            <button type="submit" class="btn btn-primary w-100">Save Build</button>
                        </form>
                    <?php else: ?>
                        <div class="mt-3 text-center">
                            <a href="login.php" class="btn btn-primary">Login to Save Build</a>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
            
            <div class="mt-3 d-flex justify-between">
                <button id="btn-prev" class="btn btn-outline" style="visibility: hidden;">Previous</button>
                <button id="btn-next" class="btn btn-primary" disabled>Next</button> <!-- Disabled until selection made -->
            </div>
        </div>
    </div>

    <!-- Sidebar Summary -->
    <div style="flex: 1;">
        <div class="card" style="position: sticky; top: 1rem;">
            <div class="card-header">Current Build</div>
            <ul id="mini-summary" class="mb-2">
                <!-- Selected parts list -->
            </ul>
            <div style="border-top: 1px solid var(--color-border); padding-top: 1rem;">
                <div class="d-flex justify-between align-center mb-1">
                    <span>Total:</span>
                    <span class="summary-total">₹<span id="total-price">0</span></span>
                </div>
                <div id="budget-status" class="budget-warning" style="display: none;">
                    Over Budget!
                </div>
            </div>
        </div>
    </div>
</div>

<script src="assets/js/builder.js"></script>

<?php include 'includes/footer.php'; ?>