<?php
require_once 'includes/db.php';
require_once 'includes/user-auth.php';

requireLogin();

if (!isset($_GET['id'])) {
    die("Build ID required.");
}

$build_id = $_GET['id'];

// Fetch build details with all part names
$stmt = $pdo->prepare("
    SELECT b.*, 
           cpu.name as cpu_name, cpu.price as cpu_price,
           mobo.name as mobo_name, mobo.price as mobo_price,
           ram.name as ram_name, ram.price as ram_price,
           storage.name as storage_name, storage.price as storage_price,
           gpu.name as gpu_name, gpu.price as gpu_price,
           psu.name as psu_name, psu.price as psu_price
    FROM builds b
    LEFT JOIN parts cpu ON b.cpu_id = cpu.id
    LEFT JOIN parts mobo ON b.motherboard_id = mobo.id
    LEFT JOIN parts ram ON b.ram_id = ram.id
    LEFT JOIN parts storage ON b.storage_id = storage.id
    LEFT JOIN parts gpu ON b.gpu_id = gpu.id
    LEFT JOIN parts psu ON b.psu_id = psu.id
    WHERE b.id = ? AND b.user_id = ?
");
$stmt->execute([$build_id, $_SESSION['user_id']]);
$build = $stmt->fetch();

if (!$build) {
    die("Build not found or access denied.");
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Build Summary #<?php echo $build['id']; ?></title>
    <style>
        body { font-family: sans-serif; padding: 2rem; max-width: 800px; margin: 0 auto; }
        h1 { text-align: center; border-bottom: 2px solid #eee; padding-bottom: 1rem; }
        .row { display: flex; justify-content: space-between; padding: 1rem 0; border-bottom: 1px solid #eee; }
        .label { font-weight: bold; }
        .total { font-size: 1.5rem; font-weight: bold; text-align: right; margin-top: 2rem; }
        .footer { margin-top: 3rem; text-align: center; font-size: 0.8rem; color: #666; }
        @media print {
            .no-print { display: none; }
        }
    </style>
</head>
<body>
    <div class="no-print" style="margin-bottom: 2rem; text-align: center;">
        <button onclick="window.print()" style="padding: 0.5rem 1rem; cursor: pointer; background: #2dba4e; color: white; border: none; border-radius: 4px;">Download/Print PDF</button>
        <a href="my-builds.php" style="margin-left: 1rem; color: #666;">Back</a>
    </div>

    <h1>PCForge Build Summary</h1>
    <p><strong>Date:</strong> <?php echo date('F d, Y', strtotime($build['created_at'])); ?></p>
    
    <div class="row">
        <span class="label">CPU</span>
        <span><?php echo $build['cpu_name']; ?></span>
        <span>₹<?php echo number_format($build['cpu_price']); ?></span>
    </div>
    <div class="row">
        <span class="label">Motherboard</span>
        <span><?php echo $build['mobo_name']; ?></span>
        <span>₹<?php echo number_format($build['mobo_price']); ?></span>
    </div>
    <div class="row">
        <span class="label">RAM</span>
        <span><?php echo $build['ram_name']; ?></span>
        <span>₹<?php echo number_format($build['ram_price']); ?></span>
    </div>
    <div class="row">
        <span class="label">Storage</span>
        <span><?php echo $build['storage_name']; ?></span>
        <span>₹<?php echo number_format($build['storage_price']); ?></span>
    </div>
    <div class="row">
        <span class="label">GPU</span>
        <span><?php echo $build['gpu_name']; ?></span>
        <span>₹<?php echo number_format($build['gpu_price']); ?></span>
    </div>
    <div class="row">
        <span class="label">Power Supply</span>
        <span><?php echo $build['psu_name']; ?></span>
        <span>₹<?php echo number_format($build['psu_price']); ?></span>
    </div>

    <div class="total">
        Total Cost: ₹<?php echo number_format($build['total_price']); ?>
    </div>

    <div class="footer">
        Generated by PCForge
    </div>
    
    <script>
        // Automatically trigger print on load
        window.onload = function() {
            // window.print(); 
        }
    </script>
</body>
</html>